# Generated by Django 5.0.2 on 2025-05-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='song',
            name='deezer_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Deezer ID'),
        ),
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Deezer превью'),
        ),
    ]
