# Generated by Django 5.2 on 2025-05-15 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_song_cover_url_song_deezer_id_song_preview_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Поисковый запрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История поиска',
                'verbose_name_plural': 'История поиска',
                'ordering': ['-created_at'],
            },
        ),
    ]
