# Generated by Django 6.0.5 on 2026-05-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='Мой плейлист', max_length=21, verbose_name='Название плейлиста'),
        ),
    ]
